version: 2.1
commands: # a reusable command with parameters
  print_pipeline_id:
    description: "A very simple command for printing print_pipeline_id"
    parameters:
      to:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>

jobs:
  my_job: #this job is calling the command created above
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

  fail-job: #This job is intended to fail in order to demonstrae when: fails
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo output.txt #Note that: output.txt does not exist so this will result in an error
      - run:
          name: Upload Failed Tests
          command: echo "Error found in a previous step. See one of the previous steps for more informatio"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - my_job
      - fail-job
